name: Build and Deploy to Remote Server with ttl.sh

on:
  push:
    branches:
      - develop-vue
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set image name
        id: image_name
        run: echo "IMAGE_NAME=lockify-e9e271fe-9b3d-4608-8f93-c6a66cc34831" >> $GITHUB_ENV

      - name: Build Docker image and push to ttl.sh
        run: |
          docker build -t ttl.sh/${{ env.IMAGE_NAME }}:1h .
          docker push ttl.sh/${{ env.IMAGE_NAME }}:1h
